# Default configurations for Spark
spark.master                     spark://spark-master:7077
spark.eventLog.enabled            true
spark.eventLog.dir                file:/opt/spark/tmp/spark-events
spark.history.fs.logDirectory     file:/opt/spark/tmp/spark-events
spark.sql.shuffle.partitions      2

# Where Spark downloads and caches jars (Ivy cache)
spark.jars.ivy                   /opt/spark/.ivy2
